### ISSUE TITLE
Better adopt ISO standards for date 

### ISSUE THREAD

**Issue by rajaram5** [ejp-rd-vp/ERN-common-data-elements#13]
In the `personal information` module use ISO standards to represent `birthdate`. 

Note: This issue is reported by @ronaldcornet via email

**Comment by rajaram5** [comment]
@ronaldcornet We use `xsd:dateTime` in the current model. Do you think `xsd:dateTime` creates mix-up?

**Comment by ronaldcornet** [comment]
I guess this is actually a non-issue. I find this quote about xsd:dateTime:
This datatype describes instances identified by the combination of a date and a time. Its value space is described as a combination of date and time of day in Chapter 5.4 of ISO 8601. Its lexical space is the extended format: [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]
See http://books.xmlschemata.org/relaxng/ch19-77049.html

So I close it.
