### ISSUE TITLE
Mislabels in module Disease History and Diagnosis

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/ERN-common-data-elements#19]
The "symptom age value" types are not correctly labeled and advice the changes:

hp:Antenatal -> hp: Antenatal onset (see: http://purl.obolibrary.org/obo/HP_0030674)
hp:At birth -> hp: Congenital onset  (see: http://purl.obolibrary.org/obo/HP_0003577) 

The suggested labels can also make them look different from those for the "diagnosis age value" types.

**Comment by rajaram5** [comment]
@sxzhang1201 I am changing it. In general, we can also use this a rule while drawing.
