### ISSUE TITLE
Lists of Ontology(ies)

### ISSUE THREAD

**Issue by S2Ola** [ejp-rd-vp/ERN-common-data-elements#23]
What are the ontologies that are been consider for the CDE in ERN? 
A list of preferred ontology should be created e.g. 

- SIO 
- NCIT etc

**Comment by nirupamaBenis** [comment]
I made a page in the wiki with the list of ontologies. 
https://github.com/ejp-rd-vp/ERN-common-data-elements/wiki/List-of-Ontologies-in-the-model
